logging:
  level:
    ROOT: DEBUG
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: instrument-portfolio
          uri: http://localhost:8081/
          predicates:
            - Path=/instrument/**
        - id: second-microservice
          uri: http://localhost:8082/
          predicates:
            - Path=/instrument/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8082/realms/master/protocol/openid-connect/certs"